# Generated by Django 4.2 on 2023-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myBlogApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(default="DEFAULT VALUE", upload_to="images"),
        ),
    ]
