# Generated by Django 4.2 on 2023-01-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myBlogApp", "0002_post_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="img",
            new_name="image",
        ),
    ]
