# Generated by Django 4.2 on 2023-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myBlogApp", "0003_rename_img_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="image vide", upload_to="images/"),
        ),
    ]
